package dao;
// Generated May 23, 2018 12:39:58 PM by Hibernate Tools 4.3.1



/**
 * Caixa generated by hbm2java
 */
public class Caixa  implements java.io.Serializable {


     private CaixaId id;
     private Armazem armazem;
     private Produto produto;
     private short idcaixa;
     private short quantidade;

    public Caixa() {
    }

    public Caixa(CaixaId id, Armazem armazem, Produto produto, short idcaixa, short quantidade) {
       this.id = id;
       this.armazem = armazem;
       this.produto = produto;
       this.idcaixa = idcaixa;
       this.quantidade = quantidade;
    }
   
    public CaixaId getId() {
        return this.id;
    }
    
    public void setId(CaixaId id) {
        this.id = id;
    }
    public Armazem getArmazem() {
        return this.armazem;
    }
    
    public void setArmazem(Armazem armazem) {
        this.armazem = armazem;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public short getIdcaixa() {
        return this.idcaixa;
    }
    
    public void setIdcaixa(short idcaixa) {
        this.idcaixa = idcaixa;
    }
    public short getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(short quantidade) {
        this.quantidade = quantidade;
    }




}


