package dao;
// Generated May 23, 2018 12:39:58 PM by Hibernate Tools 4.3.1



/**
 * CaixaId generated by hbm2java
 */
public class CaixaId  implements java.io.Serializable {


     private byte idarmazem;
     private long codbarras;

    public CaixaId() {
    }

    public CaixaId(byte idarmazem, long codbarras) {
       this.idarmazem = idarmazem;
       this.codbarras = codbarras;
    }
   
    public byte getIdarmazem() {
        return this.idarmazem;
    }
    
    public void setIdarmazem(byte idarmazem) {
        this.idarmazem = idarmazem;
    }
    public long getCodbarras() {
        return this.codbarras;
    }
    
    public void setCodbarras(long codbarras) {
        this.codbarras = codbarras;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CaixaId) ) return false;
		 CaixaId castOther = ( CaixaId ) other; 
         
		 return (this.getIdarmazem()==castOther.getIdarmazem())
 && (this.getCodbarras()==castOther.getCodbarras());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdarmazem();
         result = 37 * result + (int) this.getCodbarras();
         return result;
   }   


}


