package dao;
// Generated May 23, 2018 12:39:58 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Desconto generated by hbm2java
 */
public class Desconto  implements java.io.Serializable {


     private BigDecimal iddesconto;
     private Date datainicio;
     private Date datafim;
     private double valor;
     private Set<Produtoloja> produtolojas = new HashSet<Produtoloja>(0);

    public Desconto() {
    }

	
    public Desconto(BigDecimal iddesconto, Date datainicio, Date datafim, double valor) {
        this.iddesconto = iddesconto;
        this.datainicio = datainicio;
        this.datafim = datafim;
        this.valor = valor;
    }
    public Desconto(BigDecimal iddesconto, Date datainicio, Date datafim, double valor, Set<Produtoloja> produtolojas) {
       this.iddesconto = iddesconto;
       this.datainicio = datainicio;
       this.datafim = datafim;
       this.valor = valor;
       this.produtolojas = produtolojas;
    }
   
    public BigDecimal getIddesconto() {
        return this.iddesconto;
    }
    
    public void setIddesconto(BigDecimal iddesconto) {
        this.iddesconto = iddesconto;
    }
    public Date getDatainicio() {
        return this.datainicio;
    }
    
    public void setDatainicio(Date datainicio) {
        this.datainicio = datainicio;
    }
    public Date getDatafim() {
        return this.datafim;
    }
    
    public void setDatafim(Date datafim) {
        this.datafim = datafim;
    }
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }
    public Set<Produtoloja> getProdutolojas() {
        return this.produtolojas;
    }
    
    public void setProdutolojas(Set<Produtoloja> produtolojas) {
        this.produtolojas = produtolojas;
    }




}


