package dao;
// Generated May 23, 2018 12:39:58 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Horario generated by hbm2java
 */
public class Horario  implements java.io.Serializable {


     private BigDecimal idhorario;
     private Date horaprimeiraentrada;
     private Date horaprimeirasaida;
     private Date horasegundaentrada;
     private Date horasegundasaida;
     private Set<Funcionario> funcionarios = new HashSet<Funcionario>(0);
     private Set<Pontohorario> pontohorarios = new HashSet<Pontohorario>(0);

    public Horario() {
    }

	
    public Horario(BigDecimal idhorario, Date horaprimeiraentrada, Date horaprimeirasaida, Date horasegundaentrada, Date horasegundasaida) {
        this.idhorario = idhorario;
        this.horaprimeiraentrada = horaprimeiraentrada;
        this.horaprimeirasaida = horaprimeirasaida;
        this.horasegundaentrada = horasegundaentrada;
        this.horasegundasaida = horasegundasaida;
    }
    public Horario(BigDecimal idhorario, Date horaprimeiraentrada, Date horaprimeirasaida, Date horasegundaentrada, Date horasegundasaida, Set<Funcionario> funcionarios, Set<Pontohorario> pontohorarios) {
       this.idhorario = idhorario;
       this.horaprimeiraentrada = horaprimeiraentrada;
       this.horaprimeirasaida = horaprimeirasaida;
       this.horasegundaentrada = horasegundaentrada;
       this.horasegundasaida = horasegundasaida;
       this.funcionarios = funcionarios;
       this.pontohorarios = pontohorarios;
    }
   
    public BigDecimal getIdhorario() {
        return this.idhorario;
    }
    
    public void setIdhorario(BigDecimal idhorario) {
        this.idhorario = idhorario;
    }
    public Date getHoraprimeiraentrada() {
        return this.horaprimeiraentrada;
    }
    
    public void setHoraprimeiraentrada(Date horaprimeiraentrada) {
        this.horaprimeiraentrada = horaprimeiraentrada;
    }
    public Date getHoraprimeirasaida() {
        return this.horaprimeirasaida;
    }
    
    public void setHoraprimeirasaida(Date horaprimeirasaida) {
        this.horaprimeirasaida = horaprimeirasaida;
    }
    public Date getHorasegundaentrada() {
        return this.horasegundaentrada;
    }
    
    public void setHorasegundaentrada(Date horasegundaentrada) {
        this.horasegundaentrada = horasegundaentrada;
    }
    public Date getHorasegundasaida() {
        return this.horasegundasaida;
    }
    
    public void setHorasegundasaida(Date horasegundasaida) {
        this.horasegundasaida = horasegundasaida;
    }
    public Set<Funcionario> getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set<Funcionario> funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Set<Pontohorario> getPontohorarios() {
        return this.pontohorarios;
    }
    
    public void setPontohorarios(Set<Pontohorario> pontohorarios) {
        this.pontohorarios = pontohorarios;
    }




}


