package dao;
// Generated May 23, 2018 12:39:58 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Pontossaida generated by hbm2java
 */
public class Pontossaida  implements java.io.Serializable {


     private BigDecimal idpontossaida;
     private Pontohorario pontohorario;

    public Pontossaida() {
    }

    public Pontossaida(BigDecimal idpontossaida, Pontohorario pontohorario) {
       this.idpontossaida = idpontossaida;
       this.pontohorario = pontohorario;
    }
   
    public BigDecimal getIdpontossaida() {
        return this.idpontossaida;
    }
    
    public void setIdpontossaida(BigDecimal idpontossaida) {
        this.idpontossaida = idpontossaida;
    }
    public Pontohorario getPontohorario() {
        return this.pontohorario;
    }
    
    public void setPontohorario(Pontohorario pontohorario) {
        this.pontohorario = pontohorario;
    }




}


