package dao;
// Generated May 23, 2018 12:39:58 PM by Hibernate Tools 4.3.1



/**
 * ProdutoentregaId generated by hbm2java
 */
public class ProdutoentregaId  implements java.io.Serializable {


     private long codbarras;
     private int identrega;

    public ProdutoentregaId() {
    }

    public ProdutoentregaId(long codbarras, int identrega) {
       this.codbarras = codbarras;
       this.identrega = identrega;
    }
   
    public long getCodbarras() {
        return this.codbarras;
    }
    
    public void setCodbarras(long codbarras) {
        this.codbarras = codbarras;
    }
    public int getIdentrega() {
        return this.identrega;
    }
    
    public void setIdentrega(int identrega) {
        this.identrega = identrega;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProdutoentregaId) ) return false;
		 ProdutoentregaId castOther = ( ProdutoentregaId ) other; 
         
		 return (this.getCodbarras()==castOther.getCodbarras())
 && (this.getIdentrega()==castOther.getIdentrega());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCodbarras();
         result = 37 * result + this.getIdentrega();
         return result;
   }   


}


