package dao;
// Generated May 23, 2018 12:39:58 PM by Hibernate Tools 4.3.1



/**
 * Produtoloja generated by hbm2java
 */
public class Produtoloja  implements java.io.Serializable {


     private ProdutolojaId id;
     private Desconto desconto;
     private Loja loja;
     private Produto produto;
     private short quantidade;

    public Produtoloja() {
    }

    public Produtoloja(ProdutolojaId id, Desconto desconto, Loja loja, Produto produto, short quantidade) {
       this.id = id;
       this.desconto = desconto;
       this.loja = loja;
       this.produto = produto;
       this.quantidade = quantidade;
    }
   
    public ProdutolojaId getId() {
        return this.id;
    }
    
    public void setId(ProdutolojaId id) {
        this.id = id;
    }
    public Desconto getDesconto() {
        return this.desconto;
    }
    
    public void setDesconto(Desconto desconto) {
        this.desconto = desconto;
    }
    public Loja getLoja() {
        return this.loja;
    }
    
    public void setLoja(Loja loja) {
        this.loja = loja;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public short getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(short quantidade) {
        this.quantidade = quantidade;
    }




}


