package dao;
// Generated May 23, 2018 12:39:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipopagamento generated by hbm2java
 */
public class Tipopagamento  implements java.io.Serializable {


     private byte idtipopagamento;
     private String nome;
     private Set<Venda> vendas = new HashSet<Venda>(0);

    public Tipopagamento() {
    }

	
    public Tipopagamento(byte idtipopagamento, String nome) {
        this.idtipopagamento = idtipopagamento;
        this.nome = nome;
    }
    public Tipopagamento(byte idtipopagamento, String nome, Set<Venda> vendas) {
       this.idtipopagamento = idtipopagamento;
       this.nome = nome;
       this.vendas = vendas;
    }
   
    public byte getIdtipopagamento() {
        return this.idtipopagamento;
    }
    
    public void setIdtipopagamento(byte idtipopagamento) {
        this.idtipopagamento = idtipopagamento;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Venda> getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set<Venda> vendas) {
        this.vendas = vendas;
    }




}


