package dao;
// Generated May 23, 2018 12:39:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

/**
 * Tipoproduto generated by hbm2java
 */
public class Tipoproduto  implements java.io.Serializable {
    
     private byte idtipoproduto;
     private String nome;
     private Set<Produto> produtos = new HashSet<Produto>(0);

    public Tipoproduto() {
    }

	
    public Tipoproduto(byte idtipoproduto, String nome) {
        this.idtipoproduto = idtipoproduto;
        this.nome = nome;
    }
    public Tipoproduto(byte idtipoproduto, String nome, Set<Produto> produtos) {
       this.idtipoproduto = idtipoproduto;
       this.nome = nome;
       this.produtos = produtos;
    }
   
    public byte getIdtipoproduto() {
        return this.idtipoproduto;
    }
    
    public void setIdtipoproduto(byte idtipoproduto) {
        this.idtipoproduto = idtipoproduto;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Produto> getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set<Produto> produtos) {
        this.produtos = produtos;
    }
    
    @Override
    public String toString(){
        return this.getNome();
    }



}


